trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  inputs:
    containerRegistry: 'edburns0docker'
    repository: 'edburns0docker/azure-cafe'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'v3'
- task: Kubernetes@1
  continueOnError: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-cafe-cluster-ejb1203p'
    command: 'delete'
    useConfigurationFile: true
    configuration: 'azure-cafe.yml'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-cafe-cluster-ejb1203p'
    command: 'create'
    useConfigurationFile: true
    configuration: 'azure-cafe.yml'
    forceUpdateConfigMap: true
    configMapName: 'application-insights-key'
    configMapArguments: '--from-literal=APPLICATION_INSIGHTS_KEY=8360b67f-52a4-4a5a-a2e4-bbf72d78409e'
